### ISSUE TITLE
S3 Duplicate Files

### ISSUE THREAD

**Issue by davidtaylorhq** [Bakual/SermonSpeaker#32]
No error is shown when uploading a file to S3 when a file already exists with that name. 

Instead, the file is overwritten with no warning.

**Comment by Bakual** [comment]
I'm not sure if the API allows to check the file presence first, but I'll have a look.

**Comment by Bakual** [comment]
@davidtaylorhq This one should do the trick. I don't have an API in the S3 class I use to directly prevent overwrites. Thus I do now a check first myself before uploading.
Can you verify it works as expected (date/language "folder" is included here as well)

[com_sermonspeaker.zip](https://github.com/Bakual/SermonSpeaker/files/130778/com_sermonspeaker.zip)

**Comment by davidtaylorhq** [comment]
This works perfectly as far as I can see - thank you!
