### ISSUE TITLE
S3 Folder Structure

### ISSUE THREAD

**Issue by davidtaylorhq** [Bakual/SermonSpeaker#33]
When using the S3 storage option, the "Monthly subdirectories" option is not followed. This can result in a very long list of sermons, which is not user friendly.

**Comment by Bakual** [comment]
S3 doesn't allow folders. Thus this feature isn't possible with Amazon S3.

**Comment by davidtaylorhq** [comment]
While AWS does not have folders in the traditional sense, the functionality can be emulated using key name prefixes, see here: http://docs.aws.amazon.com/AmazonS3/latest/UG/FolderOperations.html

**Comment by Bakual** [comment]
I can have a look if the S3 library I use does support reading such a "folder".

**Comment by Bakual** [comment]
@davidtaylorhq Can you try the attached version, it now supports "folders" in Amazon S3.
I hope I catched every instance where this applies :smile: 

[com_sermonspeaker.zip](https://github.com/Bakual/SermonSpeaker/files/130725/com_sermonspeaker.zip)

**Comment by davidtaylorhq** [comment]
This works - thanks
