### ISSUE TITLE
S3 Bucket Custom URL

### ISSUE THREAD

**Issue by davidtaylorhq** [Bakual/SermonSpeaker#34]
Currently S3 buckets are addressed as 

    http://s3-<region>.amazonaws.com/<bucket-name>

By setting the name of a bucket to a full domain name (like sermons.example.com), and adding an appropriate 'CNAME' DNS entry it is possible to access your bucket with a custom domain name. See here: http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html

So instead of 

    http://s3-<region>.amazonaws.com/<bucket-name>/sermon.mp3

 you would have

    http://sermons.example.com/sermon.mp3

This looks a lot smarter, and it would be great if sermonspeaker can support it.

Implementing would require an additional field in the configuration - maybe "Custom Bucket URL", and then appropriate changes, probably in all the same places as the changes in cad4528

**Comment by Bakual** [comment]
It's a bit hard to test for me, but implementing should be easy. Do you have access to such a domain?

**Comment by davidtaylorhq** [comment]
I have just emailed you with the address & credentials of a bucket you are welcome to use for testing

**Comment by Bakual** [comment]
Thanks and implemented :smile:
