### ISSUE TITLE
Player in detail page

### ISSUE THREAD

**Issue by davidtaylorhq** [Bakual/SermonSpeaker#35]
When using the new "plugin" based player functionality, I get the error "No matching player found" on the sermon detail pages. It works fine on the modules & on the sermon list views. Tried with a fresh install of the latest release and had the same issue.

<img width="964" alt="screen shot 2016-02-23 at 10 24 50" src="https://cloud.githubusercontent.com/assets/6270921/13248702/d58600b6-da17-11e5-9cc3-48f7a4951ab0.png">

If I change from "-Use Plugin" to "JW Player 6" then it works fine.

**Comment by Bakual** [comment]
The icon layout is a bit special, it requires the pixelout player (http://www.sermonspeaker.net/download/player-pixelout.html).
The other players don't look nice in this layout.
