### ISSUE TITLE
CDN support

### ISSUE THREAD

**Issue by guoxiangke** [Bakual/SermonSpeaker#78]
Hi， I use  JCH 6.1.1   https://extensions.joomla.org/extension/jch-optimize/   to add CDN to my Joomla site.
but the Sermon files I uploaded show use relative path with the main domain instead of the CDN domain.
does this plugin support cdn.
plz support, thanks.

**Comment by Bakual** [comment]
SermonSpeaker supports Amazon S3 as storage for the sermon files. I have no clue what JCH Optimize does, but I can imagine that this doesn't work with SermonSpeaker.
What exactly doesn't work? The Download or the player or backend?

**Comment by guoxiangke** [comment]
For example, 
before is : https://mydomain.com/images/intro/programs_bp.png
After is : https://**cdn.**mydomain.com/images/intro/programs_bp.png
but the mp3 I uploaded not:
before src is: /bp/audio/20201209.mp3
now src also: /bp/audio/20201209.mp3
and the < audio> tag always: https://mydomain.com/bp/audio/20201209.mp3 
what we except is : https://**cdn.**mydomain.com/bp/audio/20201209.mp3

**Comment by guoxiangke** [comment]
I think this plugin also the same, if not support:
https://extensions.joomla.org/extension/cdn-for-joomla/

**Comment by Bakual** [comment]
I had a look at their site to see how the plugin works. As far as I understand it, there is nothing I could do on my part which enables support for this. This should be entirely in the realm of the plugin.
Can you ask their support to look at it? And if I have to do something, they could maybe give me some hints on what I would have to do.

**Comment by guoxiangke** [comment]
here is my way to walk around.
![image](https://user-images.githubusercontent.com/1160703/104315358-cd2ec280-5515-11eb-9897-27d2c214500e.png)
