### ISSUE TITLE
Scripture rendering

### ISSUE THREAD

**Issue by brendan-pike** [Bakual/SermonSpeaker#84]
I'm not sure if this is a bug with sermonspeaker or the biblegateway js. Please just close if its with biblegateway.

If you look here, [https://httn.net/audio-teachings/sermon/51-the-transformation-process](https://httn.net/audio-teachings/sermon/51-the-transformation-process) you'll see the last scripture reference at the top (2 Corinthians 4:1-6) is not hyper linked. 

Any ideas?

**Comment by Bakual** [comment]
Aw, sorry. I missed this issue.
Looks indeed like the biblegateway code does something funny. It detects the number from the book (eg "1" in "1 Peter") as an additional verse from the previous scripture reference.
I'm not sure from your description how you integrated biblegateway. Is that a generic code which scans the whole page or is it a plugin which is triggered from plugin tags?

**Comment by brendan-pike** [comment]
Wow, I lost track of this sorry.  I used this https://www.biblegateway.com/share/#reftag I understand now clearly its nothing to do sermonspeaker so I'll close this ticket.
